import { defineField, defineType } from 'sanity'

const videoSlotDefaults = [
  ['Hero Feature', 'Portrait Clip', 'Hero'],
  ['Intro Sample', 'Creator Intro', 'About'],
  ['AI Persona', 'Ad Read Test', 'About / AI UGC Samples'],
  ['Product Demo', 'Wide Sample', 'AI UGC Samples'],
  ['Brand Story', 'Wide Sample', 'AI UGC Samples'],
  ['ForceFactor', 'Supplements', 'Medical Wellness'],
  ['UmiGlow', 'Greens Powder', 'Medical Wellness'],
  ['Nugenix Total T2', "Men's Health", 'Medical Wellness'],
  ['Sky Nutrition', 'Memory Gummies', 'Medical Wellness'],
  ['Glow Serum', 'Skincare Demo', 'Skincare and Hair Care'],
  ['Hair Repair', 'Routine Video', 'Skincare and Hair Care'],
  ['SPF Daily', 'Face Care', 'Skincare and Hair Care'],
  ['Volume Spray', 'Hair Tutorial', 'Skincare and Hair Care'],
  ['Sampeel Lounge Wear', 'Amazon Video', 'Lifestyle and Home'],
  ['Fresh Produce', 'T-Shirt Everywhere Dress', 'Lifestyle and Home'],
  ['BeyondDiamond', 'Sponsored Content', 'Lifestyle and Home'],
  ['Velantra Boat Tote', 'Everyday Summer Bag', 'Lifestyle and Home'],
  ['Founder Script', 'Brand Voice', 'Founder-Led Scripts'],
  ['Service Brand', 'Explainer Ad', 'Founder-Led Scripts'],
  ['Coaching Offer', 'Authority Clip', 'Founder-Led Scripts'],
  ['Local Business', 'Trust Builder', 'Founder-Led Scripts'],
  ['Beauty App', 'Screen Walkthrough', 'App and SaaS UGC'],
  ['Wellness Tracker', 'Feature Demo', 'App and SaaS UGC'],
  ['Finance Tool', 'Problem/Solution', 'App and SaaS UGC'],
  ['Learning App', 'User Journey', 'App and SaaS UGC'],
  ['Retargeting', 'Objection Handler', 'Paid Ad Hooks'],
  ['Launch Offer', 'Direct CTA', 'Paid Ad Hooks'],
  ['Problem Hook', 'Before/After', 'Paid Ad Hooks'],
  ['Social Proof', 'Review Style', 'Paid Ad Hooks'],
  ['Kitchen Find', 'Home Demo', 'Home and Daily Finds'],
  ['Desk Setup', 'Lifestyle Demo', 'Home and Daily Finds'],
  ['Travel Bag', 'Packing Demo', 'Home and Daily Finds'],
  ['Pet Care', 'Routine Demo', 'Home and Daily Finds'],
  ['Full Story', 'Complete Ad', 'Video Variations'],
  ['Hook 1', 'Problem/Solution', 'Video Variations'],
  ['Hook 2', 'Text Overlay', 'Video Variations'],
  ['Hook 3', 'Direct CTA', 'Video Variations'],
  ['Contact Sample', 'Final Clip', 'Contact Footer'],
  ['Reserved', 'Campaign Add-On', 'Reserved'],
  ['Reserved', 'Campaign Add-On', 'Reserved'],
]

const videoSlotsInitialValue = videoSlotDefaults.map(([brand, title, category], index) => ({
  slotNumber: index + 1,
  brand,
  title,
  category,
}))

export default defineType({
  name: 'siteSettings',
  title: 'Website Content',
  type: 'document',
  groups: [
    { name: 'navigation', title: 'Navigation' },
    { name: 'hero', title: 'Hero' },
    { name: 'about', title: 'About' },
    { name: 'brandTrust', title: 'Brand Trust' },
    { name: 'portfolio', title: 'Portfolio Sections' },
    { name: 'videos', title: 'Numbered Videos' },
    { name: 'variations', title: 'Video Variations' },
    { name: 'contact', title: 'Contact / Footer' },
  ],
  initialValue: {
    brandName: 'MediaCrux',
    eyebrow: 'AI UGC Creator',
    navAboutLabel: 'About',
    navPortfolioLabel: 'Portfolio',
    navContactLabel: 'Contact',
    heroHeadline: 'AI UGC ads made for brands that need speed, polish, and conversion.',
    heroSubheadline: 'Creator-style product videos, hooks, demos, and paid ad variations.',
    aboutHeading: "Hi, we're MediaCrux",
    creatorName: 'MediaCrux',
    creatorBio:
      'AI UGC studio producing human-feeling brand videos for paid media, organic social, product pages, and creator-style campaigns.',
    aboutBullets: [
      'AI-led UGC production for brands that need fresh creative quickly',
      'Product demos, testimonials, story-based ads, hooks, and CTA variations',
      'Script writing, avatar direction, editing, captions, and usage-ready exports',
      'Built for health, wellness, beauty, lifestyle, tech, and service brands',
    ],
    brandTrustEyebrow: 'Brands That Trust MediaCrux',
    brandTrustHeadline: 'UGC ads for brands ready to move faster',
    brandLogos: [
      { name: 'Wellness Brand' },
      { name: 'Beauty Brand' },
      { name: 'Lifestyle Brand' },
      { name: 'Tech Brand' },
      { name: 'Home Brand' },
      { name: 'Retail Brand' },
      { name: 'Fitness Brand' },
      { name: 'SaaS Brand' },
      { name: 'Fashion Brand' },
      { name: 'DTC Brand' },
    ],
    samplesHeading: 'AI UGC ad samples in motion',
    variationsSectionTitle: 'Video Variations',
    variationsHeadline: 'Two or More?',
    variations: [
      {
        title: 'Tell a Full Story',
        body: 'One video introduces your product, chosen AI face or spokesperson, pain point, benefit, and next step.',
      },
      {
        title: 'Test More Hooks',
        body: 'Create multiple versions from the same campaign angle so the brand can test what converts.',
      },
      {
        title: 'Match the Platform',
        body: 'Use different pacing, captions, and CTA styles for TikTok, Instagram, Shorts, and paid ads.',
      },
    ],
    sectionTitles: {
      medicalWellness: 'Medical Wellness',
      skincareHairCare: 'Skincare and Hair Care',
      lifestyleHome: 'Lifestyle and Home',
      founderLedScripts: 'Founder-Led Scripts',
      appSaasUgc: 'App and SaaS UGC',
      paidAdHooks: 'Paid Ad Hooks',
      homeDailyFinds: 'Home and Daily Finds',
    },
    location: 'Available worldwide',
    contactEmail: 'hello@mediacrux.com',
    instagramUrl: '#',
    tiktokUrl: '#',
    xUrl: '#',
    stats: [
      { value: '8.5K', label: 'TikTok' },
      { value: '23K', label: 'Instagram' },
      { value: '4.5K', label: 'X' },
    ],
    videoSlots: videoSlotsInitialValue,
    finalHeadline: 'Want to work together?',
    finalText:
      'Send the campaign brief, product details, or rough idea and MediaCrux can turn it into UGC-ready content.',
  },
  fields: [
    defineField({
      name: 'brandName',
      title: 'Brand Name',
      type: 'string',
      group: 'hero',
      description: 'Used for the mobile hero brand name, footer brand name, and logo alt text.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'eyebrow',
      title: 'Small Brand Label',
      type: 'string',
      group: 'hero',
      description: 'Small label used in footer details and fallback content.',
    }),
    defineField({ name: 'navAboutLabel', title: 'Nav Link: About', type: 'string', group: 'navigation' }),
    defineField({ name: 'navPortfolioLabel', title: 'Nav Link: Portfolio', type: 'string', group: 'navigation' }),
    defineField({ name: 'navContactLabel', title: 'Nav Link: Contact', type: 'string', group: 'navigation' }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline Backup',
      type: 'string',
      group: 'hero',
      description: 'Kept for future hero text if needed. The current live hero uses the edited banner image plus brand name.',
    }),
    defineField({
      name: 'heroSubheadline',
      title: 'Hero Subheadline Backup',
      type: 'text',
      rows: 3,
      group: 'hero',
      description: 'Kept for future hero text if needed. The current live hero uses the edited banner image plus brand name.',
    }),
    defineField({
      name: 'aboutHeading',
      title: 'About Section Heading',
      type: 'string',
      group: 'about',
      description: 'Main heading above the about paragraph.',
    }),
    defineField({
      name: 'creatorName',
      title: 'Creator / Studio Name',
      type: 'string',
      group: 'about',
      description: 'Used as the studio name fallback.',
    }),
    defineField({
      name: 'creatorBio',
      title: 'About Intro Text',
      type: 'text',
      rows: 4,
      group: 'about',
    }),
    defineField({
      name: 'aboutBullets',
      title: 'About Bullet Points',
      type: 'array',
      group: 'about',
      description: 'These appear under the intro text in the About section.',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'brandTrustEyebrow',
      title: 'Brand Trust Small Heading',
      type: 'string',
      group: 'brandTrust',
    }),
    defineField({
      name: 'brandTrustHeadline',
      title: 'Brand Trust Main Heading',
      type: 'string',
      group: 'brandTrust',
    }),
    defineField({
      name: 'brandLogos',
      title: 'Brand Trust Logos',
      type: 'array',
      group: 'brandTrust',
      description: 'Add up to 10 brands that have trusted MediaCrux. Empty logo fields show clean skeleton blocks.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'name', title: 'Brand Name', type: 'string' }),
            defineField({
              name: 'logo',
              title: 'Brand Logo',
              type: 'image',
              options: { hotspot: true },
            }),
          ],
          preview: {
            select: { title: 'name', media: 'logo' },
            prepare({ title, media }) {
              return { title: title || 'Brand logo placeholder', media }
            },
          },
        },
      ],
      validation: (Rule) => Rule.max(10),
    }),
    defineField({
      name: 'samplesHeading',
      title: 'AI UGC Samples Heading',
      type: 'string',
      group: 'portfolio',
      description: 'Heading above the mixed portrait/rectangle sample videos.',
    }),
    defineField({
      name: 'sectionTitles',
      title: 'Portfolio Section Titles',
      type: 'object',
      group: 'portfolio',
      description: 'Rename the visible portfolio section headings here.',
      fields: [
        defineField({ name: 'medicalWellness', title: 'Slots 6-9: Medical Wellness', type: 'string' }),
        defineField({ name: 'skincareHairCare', title: 'Slots 10-13: Skincare and Hair Care', type: 'string' }),
        defineField({ name: 'lifestyleHome', title: 'Slots 14-17: Lifestyle and Home', type: 'string' }),
        defineField({ name: 'founderLedScripts', title: 'Slots 18-21: Founder-Led Scripts', type: 'string' }),
        defineField({ name: 'appSaasUgc', title: 'Slots 22-25: App and SaaS UGC', type: 'string' }),
        defineField({ name: 'paidAdHooks', title: 'Slots 26-29: Paid Ad Hooks', type: 'string' }),
        defineField({ name: 'homeDailyFinds', title: 'Slots 30-33: Home and Daily Finds', type: 'string' }),
      ],
    }),
    defineField({
      name: 'videoSlots',
      title: 'Numbered Video Slots',
      type: 'array',
      group: 'videos',
      description:
        'Each item maps to one website video placeholder. Open the slot number you want, upload a video, then edit its brand/title/category text.',
      initialValue: videoSlotsInitialValue,
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'slotNumber',
              title: 'Slot Number',
              type: 'number',
              description: 'Do not change this unless the website layout changes.',
              validation: (Rule) => Rule.required().min(1).max(40),
            }),
            defineField({
              name: 'brand',
              title: 'Visible Brand / Video Label',
              type: 'string',
              description: 'This appears under the video frame when captions are enabled.',
            }),
            defineField({
              name: 'title',
              title: 'Visible Caption / Product Type',
              type: 'string',
              description: 'This appears under the brand/video label.',
            }),
            defineField({
              name: 'category',
              title: 'Website Section',
              type: 'string',
              description: 'Helps you identify where this video appears on the page.',
            }),
            defineField({
              name: 'videoFile',
              title: 'Upload Video File',
              type: 'file',
              options: { accept: 'video/*' },
              description: 'Upload directly in Sanity. If Cloudinary URL is filled below, Cloudinary is used first.',
            }),
            defineField({
              name: 'cloudinaryUrl',
              title: 'Cloudinary Video URL',
              type: 'url',
              description: 'Optional. Paste the Cloudinary secure URL here.',
            }),
          ],
          preview: {
            select: {
              slotNumber: 'slotNumber',
              title: 'title',
              brand: 'brand',
              subtitle: 'category',
            },
            prepare({ slotNumber, title, brand, subtitle }) {
              return {
                title: `Slot ${slotNumber || '?'} - ${subtitle || 'Website video'}`,
                subtitle: [brand, title].filter(Boolean).join(' | '),
              }
            },
          },
        },
      ],
      validation: (Rule) => Rule.required().min(38).max(40),
    }),
    defineField({
      name: 'variationsSectionTitle',
      title: 'Video Variations Section Title',
      type: 'string',
      group: 'variations',
    }),
    defineField({
      name: 'variationsHeadline',
      title: 'Video Variations Left Heading',
      type: 'string',
      group: 'variations',
    }),
    defineField({
      name: 'variations',
      title: 'Video Variations Text Blocks',
      type: 'array',
      group: 'variations',
      description: 'Text beside the Hook 1, Hook 2, and Full Story video frames.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'title', type: 'string', title: 'Heading' }),
            defineField({ name: 'body', type: 'text', title: 'Body Text', rows: 3 }),
          ],
          preview: { select: { title: 'title', subtitle: 'body' } },
        },
      ],
    }),
    defineField({ name: 'location', title: 'Footer Location Text', type: 'string', group: 'contact' }),
    defineField({ name: 'contactEmail', title: 'Contact Email', type: 'string', group: 'contact' }),
    defineField({ name: 'instagramUrl', title: 'Instagram URL', type: 'url', group: 'contact' }),
    defineField({ name: 'tiktokUrl', title: 'TikTok URL', type: 'url', group: 'contact' }),
    defineField({ name: 'xUrl', title: 'X URL', type: 'url', group: 'contact' }),
    defineField({
      name: 'stats',
      title: 'Social Stats',
      type: 'array',
      group: 'contact',
      description: 'Optional stats used as fallback/reference content.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'value', type: 'string', title: 'Value (example: 23K)' }),
            defineField({ name: 'label', type: 'string', title: 'Label (example: Instagram)' }),
          ],
          preview: { select: { title: 'value', subtitle: 'label' } },
        },
      ],
    }),
    defineField({
      name: 'finalHeadline',
      title: 'Final CTA Headline',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'finalText',
      title: 'Final CTA Text',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Website Content',
        subtitle: 'Editable text, section headings, brand logos, social links, and numbered video slots',
      }
    },
  },
})
